soon-market-realtime-service:
  application:
    logLevel: INFO
    kkLogLevel: DEBUG
    dbReadRetryMaxAttempts: 12
    dbReadRetryInterval: 5
    connection:
      url: jdbc:postgresql://dev-postgresql.development.svc:5432/SOON_MARKET
      user: SOON_MARKET
      remoteSecretProperty: PG_SOON_MARKET_PASSWORD
    kafka:
      brokers: dev-kafka-controller-headless.development.svc:9094
      connectEndpoint: http://kafka-connect.development.svc:8083/connectors
      apicurioRegistryUrl: http://apicurio-registry.development.svc:8080/apis/registry/v2
      realtimeTopic: xpr-network.realtime.avro
      realtimeConsumerGroupId: xpr-network.realtime.avro.api.consumers
      processedTopic: xpr-network.realtime.processed.avro
      processedBundleTopic: xpr-network.realtime.processed_bundle.avro
  clusterSecretStoreName: vault-kv-secret