apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  dataFrom:
    - extract:
        key: /monitoring/grafana
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  target:
    name: grafana-secrets
