apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 8.4.0
    helm:
      values: |-
        image:
          registry: quay.io
          repository: prometheus/blackbox-exporter
        resources:
          limits:
            memory: 24Mi
          requests:
            cpu: 100m
            memory: 24Mi
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 15s
              http:
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                follow_redirects: true
                preferred_ip_protocol: "ip4"
            http_backend:
              prober: http
              timeout: 15s
              http:
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                follow_redirects: true
                preferred_ip_protocol: "ip4"
                fail_if_body_not_matches_regexp:
                  - '"allHealthy":true'
        serviceMonitor:
          enabled: true
          defaults:
            additionalMetricsRelabels: {}
            additionalRelabeling: []
            labels: {}
            interval: 60s
            scrapeTimeout: 60s
            module: http_2xx
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
