apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  selector:
    app: node
  ports:
  - name: api
    protocol: TCP
    port: 8888
    targetPort: api
  - name: state-history
    protocol: TCP
    port: 8080
    targetPort: state-history