soon-market-ui:
  application:
    soonmarketApiUrl: https://soon-market-api.dev.<DOMAIN_NAME>
  ingress:
    className: nginx
    annotations:
      <CERT_MANAGER_ISSUER_ANNOTATION_1>
      <CERT_MANAGER_ISSUER_ANNOTATION_2>
      <CERT_MANAGER_ISSUER_ANNOTATION_3>
      <CERT_MANAGER_ISSUER_ANNOTATION_4>
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
    - host: beta.<DOMAIN_NAME>
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: beta-tls
      hosts:
      - beta.<DOMAIN_NAME>
