apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  dataFrom:
  - extract:
      key: /development/postgres
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStoreName }}
  target:
    name: postgres-secrets