postgresql:
  auth:
    existingSecret: postgres-secrets
  primary:
    initdb:
      scriptsConfigMap: postgres-initdb
    extraEnvVarsSecret: postgres-secrets

clusterSecretStoreName: vault-kv-secret