soon-market-api:
  application:
    logLevel: DEBUG
    connection:
      url: jdbc:postgresql://dev-postgresql.development.svc:5432/SOON_MARKET
      user: SOON_MARKET
      remoteSecretProperty: PG_SOON_MARKET_PASSWORD
    cache:
      refreshExchangeRates: PT10m
      refreshProfiles: PT1h
      refreshShieldedCollections: PT1h
      refreshMarketConfig: P1d
      refreshSupportedAssets: P1d
    collectionSocialsPrefixes: 'website:,twitter:,telegram:,instagram:,youtube:,youtube_video_link:,discord:,snipverse:,facebook:,linkedIn:,tikTok:,snipcoins:,medium:'
    spots:
      collectionId: '323154322551'
      goldAssetId: '4398046764318'
      silverTemplateId: '51066'
  ingress:
    className: nginx
    annotations:
      <CERT_MANAGER_ISSUER_ANNOTATION_1>
      <CERT_MANAGER_ISSUER_ANNOTATION_2>
      <CERT_MANAGER_ISSUER_ANNOTATION_3>
      <CERT_MANAGER_ISSUER_ANNOTATION_4>
    hosts:
    - host: soon-market-api.dev.<DOMAIN_NAME>
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: soon-market-api-tls
      hosts:
      - soon-market-api.dev.<DOMAIN_NAME>
  clusterSecretStoreName: vault-kv-secret