apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: registry/clusters/<CLUSTER_NAME>/components/monitoring
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true